# Wybierz obraz bazowy z Node.js do uruchomienia aplikacji
FROM web-app-build:error

# Ekspozycja portu, na którym będzie działać aplikacja
EXPOSE 3000

CMD 123123
# Uruchom aplikację
CMD ["yarn, "dev"]
